var mongoose = require("mongoose");
var ProSchema = mongoose.Schema({
	store_id: String,
	class3Id: String,
	stock: String,
	product_name: String,
	id: String,
	cart_tag: String,
	unit: String,
	volume: String,
	price: String,
	product_desc: String,
	promotion_tag: String,
	promotion_tag_start: String,
	promotion_tag_end: String,
	promotion_photo: String,
	middle_promotion_photo: String,
	thum_promotion_photo: String,
	bpromotion_photo: String,
	thum_min_promotion_photo: String,
	photo: String,
	thum_photo: String,
	middle_photo: String,
	bphoto: String,
	thum_min_photo: String,
	has_webp: String,
	delivery_template_id: String,
	sort: String,
	template_id: String,
	product_no: String,
	is_real_stock: String,
	oversale: String,
	nocare_stock: String,
	warehouse: String,
	store_type: String,
	seller_id: String,
	is_oversale: Number,
	cart_tag_list: Array,
	hasSale: Number,
	sale: Object,
	deliverType: String,
	isTodayDeliver: Number,
	setAlert: Number,
});

var Product = mongoose.model("Products", ProSchema);
module.exports = Product;